#!/bin/bash -ex
# executed before apply-overlay

echo "------------------------"
echo " Create a role openuser "
echo "------------------------"
#/etc/init.d/postgresql start
su -c - postgres "createuser openuser --no-superuser --createdb --no-createrole" 
cat > /tmp/openuser_changepass.sql <<"EOF"
ALTER USER openuser WITH PASSWORD 'openuser';
EOF
su -c - postgres "psql template1 -U postgres -f /tmp/openuser_changepass.sql"
#/etc/init.d/postgresql stop
